"""
Build RefacDir with Nuitka: ``python build_exe.py``.

Nuitka compiles the code to C, then to a single native executable that embeds
the Python runtime. Needs a C compiler: Xcode Command Line Tools on macOS; on
Windows, Visual Studio Build Tools, or Nuitka downloads MinGW itself. Nuitka
does not cross-compile, so run this on each target OS.

Builds inside a dedicated ``.venv-build`` at the repo root, populated from
requirements-build.txt, so packages from the active conda env or venv aren't
bundled. The venv is based on the interpreter running this script, and the exe
embeds that interpreter's runtime. ``--current-env`` builds with the running
interpreter instead; it must already have requirements-build.txt installed.

The output, dist/RefacDir (macOS/Linux) or dist\\RefacDir.exe (Windows), is
smoke-tested with ``RefacDir --smoke-test``. Other args are forwarded to
Nuitka, e.g. ``--show-scons`` or ``--jobs=4``.

The build ships pytest, pytest-qt and the test/ tree: the app's Run tests
window runs the suite so users can see the backup cases it covers.

``--headless`` builds app_headless.py instead, as dist/RefacDirHeadless(.exe):
the MCP server with no window. It installs the ``mcp`` SDK into the build venv
(the GUI build does not include it) and leaves Qt out.

``--with-oqs`` adds quantum-safe (OQS) key encapsulation: it installs
liboqs-python, finds the liboqs shared library the build interpreter loads, and
bundles it. liboqs-python builds liboqs on first import if none is installed,
which needs git, CMake and a C compiler; or point OQS_INSTALL_PATH at an
existing install. Without the option the build has no OQS, and a cache
encrypted with OQS keys cannot be read by it. Applies to either target.
"""
import os
import shutil
import subprocess
import sys
import tempfile
import time
import venv

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
VENV_DIR = os.path.join(REPO_ROOT, ".venv-build")
BUILD_DIR = os.path.join(REPO_ROOT, "build", "nuitka")
ICON_SVG = os.path.join("ui", "assets", "refacdir_icon.svg")
ICON_ICO = os.path.join(BUILD_DIR, "refacdir_icon.ico")

# Shipped files, at the same relative paths refacdir.utils.app_paths.resource_path()
# resolves them under.
DATA_DIRS = ("locale", "examples")
GUI_DATA_FILES = (ICON_SVG, "pytest.ini")
TEST_DIR = "test"
# math is also promised, but built into the interpreter.
USER_FILE_STDLIB_MODULES = (
    "re", "os", "datetime", "fnmatch", "string", "random",
    "collections", "hashlib", "pathlib",
)
# Same source as requirements-optional.txt; not on PyPI.
LIBOQS_PYTHON = "git+https://github.com/open-quantum-safe/liboqs-python.git"
# Prints the path of the liboqs shared library liboqs-python loaded.
_LIBOQS_PROBE = (
    "import oqs.oqs as m\n"
    "lib = m.native() if hasattr(m, 'native') else m._liboqs\n"
    "print(lib._name)\n"
)
# Generated by test runs, not part of the suite.
TEST_DIR_EXCLUDES = (
    "__pycache__",
    ".pytest_cache",
    os.path.join("backup", "source"),
    os.path.join("backup", "test_files"),
)


def _venv_python(venv_dir: str) -> str:
    if sys.platform == "win32":
        return os.path.join(venv_dir, "Scripts", "python.exe")
    return os.path.join(venv_dir, "bin", "python")


def _exe_name(base: str) -> str:
    return f"{base}.exe" if sys.platform == "win32" else base


def _ensure_build_venv(extra_packages=()) -> str:
    python = _venv_python(VENV_DIR)
    if not os.path.exists(python):
        print(f"Creating build venv at {VENV_DIR}")
        venv.create(VENV_DIR, with_pip=True)
    subprocess.run(
        [python, "-m", "pip", "install", "-q", "-r", os.path.join(REPO_ROOT, "requirements-build.txt"),
         *extra_packages],
        check=True,
    )
    return python


def _test_tree_files() -> list:
    """Every file under test/ except generated ones, as repo-relative paths.

    Listed one by one because --include-data-dir skips code files, and the
    suite is mostly .py files.
    """
    files = []
    root = os.path.join(REPO_ROOT, TEST_DIR)
    for dirpath, dirnames, filenames in os.walk(root):
        rel_dir = os.path.relpath(dirpath, root)
        dirnames[:] = [
            d for d in dirnames
            if os.path.normpath(os.path.join(rel_dir, d)) not in TEST_DIR_EXCLUDES
            and d not in TEST_DIR_EXCLUDES
        ]
        for name in filenames:
            files.append(os.path.relpath(os.path.join(dirpath, name), REPO_ROOT))
    return sorted(files)


def _write_windows_icon(python: str) -> None:
    """Render the SVG app icon to the .ico Nuitka needs, with the build venv's Qt."""
    os.makedirs(BUILD_DIR, exist_ok=True)
    script = (
        "import sys\n"
        "from PySide6.QtCore import Qt\n"
        "from PySide6.QtGui import QGuiApplication, QImage, QPainter\n"
        "from PySide6.QtSvg import QSvgRenderer\n"
        "app = QGuiApplication(sys.argv[:1])\n"
        "image = QImage(256, 256, QImage.Format_ARGB32)\n"
        "image.fill(Qt.transparent)\n"
        "painter = QPainter(image)\n"
        "QSvgRenderer(sys.argv[1]).render(painter)\n"
        "painter.end()\n"
        "sys.exit(0 if image.save(sys.argv[2], 'ICO') else 1)\n"
    )
    env = dict(os.environ, QT_QPA_PLATFORM="offscreen")
    subprocess.run([python, "-c", script, os.path.join(REPO_ROOT, ICON_SVG), ICON_ICO], env=env, check=True)


def _common_args(exe_name: str, unpack_prefix: str) -> list:
    # The onefile exe unpacks its runtime to this folder. A fixed path (no
    # {PID}/{TIME}) makes Nuitka keep it between runs, so only the first run
    # pays the unpacking cost. The build id gives each build its own folder so
    # a rebuilt exe never reuses a previous build's files; old folders under
    # refacdir/unpacked/ in the user cache dir are safe to delete. On Windows
    # that cache dir is %LOCALAPPDATA%, so this sits beside the app data dir's
    # configs/, cache/ and logs/; nothing the app writes goes under unpacked/.
    build_id = time.strftime("%Y%m%d-%H%M%S")
    args = [
        "--onefile",
        f"--onefile-tempdir-spec={{CACHE_DIR}}/refacdir/unpacked/{unpack_prefix}-{build_id}",
        f"--output-dir={BUILD_DIR}",
        f"--output-filename={exe_name}",
        # Lets Nuitka fetch build helpers (e.g. MinGW on Windows) without prompting.
        "--assume-yes-for-downloads",
        # keyring finds its backends, including the OS one, through package
        # metadata entry points; without it every encrypted save fails over to
        # plaintext JSON.
        "--include-distribution-metadata=keyring",
    ]
    # The user's search functions file is loaded at runtime and can only import
    # what the build contains; its template promises these.
    args += [f"--include-module={m}" for m in USER_FILE_STDLIB_MODULES]
    args += [f"--include-data-dir={d}={d}" for d in DATA_DIRS]
    if sys.platform == "win32":
        args.append(f"--windows-icon-from-ico={ICON_ICO}")
    return args


def _gui_args() -> list:
    args = [
        "--enable-plugin=pyside6",
        # The window icon is an SVG, which needs Qt's SVG image format and icon engine.
        "--include-qt-plugins=sensible,imageformats,iconengines",
        # pytest finds the pytest-qt plugin through package metadata, loads its
        # built-in plugins by module name, and pytest-qt imports QtTest by name.
        "--include-distribution-metadata=pytest",
        "--include-distribution-metadata=pytest-qt",
        "--include-package=_pytest",
        "--include-package=pytest",
        "--include-package=pytestqt",
        "--include-module=PySide6.QtTest",
        # Test modules import it; the app itself never does.
        "--include-module=app_headless",
    ]
    args += [f"--include-data-files={f}={f}" for f in GUI_DATA_FILES]
    args += [f"--include-data-files={f}={f}" for f in _test_tree_files()]
    if sys.platform == "win32":
        # No console window when started from Explorer; when started from a
        # terminal, output (e.g. the smoke test's) goes to that terminal.
        args.append("--windows-console-mode=attach")
    return args


def _headless_args() -> list:
    return [
        # Only window-bound code (refacdir/lib/position_data.py) imports Qt,
        # inside functions a headless process never calls.
        "--nofollow-import-to=PySide6",
        # The SDK reads its own version from package metadata, and uvicorn
        # loads its protocol and event-loop modules by name.
        "--include-distribution-metadata=mcp",
        "--include-package=uvicorn",
    ]


def _oqs_args(python: str, with_oqs: bool) -> list:
    if not with_oqs:
        # Keep liboqs-python out even if the build environment has it: without
        # its shared library it would try to build liboqs at the app's startup.
        return ["--nofollow-import-to=oqs"]
    probe = subprocess.run([python, "-c", _LIBOQS_PROBE], capture_output=True, text=True)
    library = probe.stdout.strip().splitlines()[-1] if probe.stdout.strip() else ""
    if probe.returncode != 0 or not os.path.isabs(library) or not os.path.isfile(library):
        sys.exit(
            "--with-oqs: could not locate the liboqs shared library through liboqs-python.\n"
            f"{probe.stdout}{probe.stderr}\n"
            "Install liboqs (or let liboqs-python build it: needs git, CMake and a C "
            "compiler) or set OQS_INSTALL_PATH to an existing install, then rebuild."
        )
    # The layout liboqs-python searches under OQS_INSTALL_PATH, which
    # refacdir/utils/encryptor.py points at this folder in the build.
    lib_dir = "bin" if sys.platform == "win32" else "lib"
    print(f"Bundling liboqs: {library}")
    return [
        "--include-package=oqs",
        "--include-distribution-metadata=liboqs-python",
        f"--include-data-files={library}=liboqs/{lib_dir}/{os.path.basename(library)}",
    ]


# name, entry script, extra pip packages, unpack folder prefix, target-specific args
TARGETS = {
    "gui": ("RefacDir", "app_qt.py", (), "refacdir", _gui_args),
    "headless": ("RefacDirHeadless", "app_headless.py", ("mcp",), "refacdir-headless", _headless_args),
}


def _smoke_test(exe_path: str, with_oqs: bool) -> None:
    # Run from outside the repo so a passing test can't depend on the checkout,
    # with all app data in a scratch directory so the user's is untouched.
    with tempfile.TemporaryDirectory(prefix="refacdir-smoke-") as scratch:
        env = dict(os.environ)
        env["QT_QPA_PLATFORM"] = "offscreen"
        env["REFACDIR_APP_DATA_DIR"] = scratch
        result = subprocess.run(
            [exe_path, "--smoke-test", *(["--expect-oqs"] if with_oqs else [])],
            cwd=os.path.expanduser("~"), env=env,
            capture_output=True, text=True, errors="replace",
        )
    sys.stdout.write(result.stdout + result.stderr)
    if result.returncode != 0:
        sys.exit(f"Smoke test failed: `{exe_path} --smoke-test` exited {result.returncode}")


if __name__ == "__main__":
    args = sys.argv[1:]
    target = "gui"
    if "--headless" in args:
        args.remove("--headless")
        target = "headless"
    with_oqs = "--with-oqs" in args
    if with_oqs:
        args.remove("--with-oqs")
    base_name, entry, extra_packages, unpack_prefix, target_args = TARGETS[target]
    if with_oqs:
        extra_packages = (*extra_packages, LIBOQS_PYTHON)
    exe_name = _exe_name(base_name)
    exe_path = os.path.join(REPO_ROOT, "dist", exe_name)

    if "--current-env" in args:
        args.remove("--current-env")
        python = sys.executable
    else:
        python = _ensure_build_venv(extra_packages)

    if sys.platform == "win32":
        _write_windows_icon(python)
    nuitka_args = [
        *_common_args(exe_name, unpack_prefix), *target_args(), *_oqs_args(python, with_oqs),
        *args, os.path.join(REPO_ROOT, entry),
    ]
    subprocess.run([python, "-m", "nuitka", *nuitka_args], cwd=REPO_ROOT, check=True)
    os.makedirs(os.path.dirname(exe_path), exist_ok=True)
    shutil.copy2(os.path.join(BUILD_DIR, exe_name), exe_path)
    _smoke_test(exe_path, with_oqs)
    print(f"Built {exe_path}")
