"""
Build RefacDir with Nuitka: ``python build_exe.py``.

Nuitka compiles the code to C, then to a single native executable that embeds
the Python runtime. Needs a C compiler: Xcode Command Line Tools on macOS; on
Windows, Visual Studio Build Tools, or Nuitka downloads MinGW itself. Nuitka
does not cross-compile, so run this on each target OS.

Builds inside a dedicated ``.venv-build`` at the repo root, populated from
requirements-build.txt, so packages from the active conda env or venv aren't
bundled. The venv is based on the interpreter running this script, and the exe
embeds that interpreter's runtime. ``--current-env`` builds with the running
interpreter instead; it must already have requirements-build.txt installed.

The output, dist/RefacDir (macOS/Linux) or dist\\RefacDir.exe (Windows), is
smoke-tested with ``RefacDir --smoke-test``. Other args are forwarded to
Nuitka, e.g. ``--show-scons`` or ``--jobs=4``.

The build ships pytest, pytest-qt and the test/ tree: the app's Run tests
window runs the suite so users can see the backup cases it covers.
"""
import os
import shutil
import subprocess
import sys
import tempfile
import time
import venv

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
VENV_DIR = os.path.join(REPO_ROOT, ".venv-build")
ENTRY = os.path.join(REPO_ROOT, "app_qt.py")
BUILD_DIR = os.path.join(REPO_ROOT, "build", "nuitka")
EXE_NAME = "RefacDir.exe" if sys.platform == "win32" else "RefacDir"
EXE_PATH = os.path.join(REPO_ROOT, "dist", EXE_NAME)
ICON_SVG = os.path.join("ui", "assets", "refacdir_icon.svg")
ICON_ICO = os.path.join(BUILD_DIR, "refacdir_icon.ico")

# Shipped files, at the same relative paths refacdir.utils.app_paths.resource_path()
# resolves them under.
DATA_DIRS = ("locale", "examples")
DATA_FILES = (ICON_SVG, "pytest.ini")
TEST_DIR = "test"
USER_FILE_STDLIB_MODULES = (
    "re", "os", "datetime", "fnmatch", "string", "math", "random",
    "collections", "hashlib", "pathlib",
)
# Generated by test runs, not part of the suite.
TEST_DIR_EXCLUDES = (
    "__pycache__",
    ".pytest_cache",
    os.path.join("backup", "source"),
    os.path.join("backup", "test_files"),
)


def _venv_python(venv_dir: str) -> str:
    if sys.platform == "win32":
        return os.path.join(venv_dir, "Scripts", "python.exe")
    return os.path.join(venv_dir, "bin", "python")


def _ensure_build_venv() -> str:
    python = _venv_python(VENV_DIR)
    if not os.path.exists(python):
        print(f"Creating build venv at {VENV_DIR}")
        venv.create(VENV_DIR, with_pip=True)
    subprocess.run(
        [python, "-m", "pip", "install", "-q", "-r", os.path.join(REPO_ROOT, "requirements-build.txt")],
        check=True,
    )
    return python


def _test_tree_files() -> list:
    """Every file under test/ except generated ones, as repo-relative paths.

    Listed one by one because --include-data-dir skips code files, and the
    suite is mostly .py files.
    """
    files = []
    root = os.path.join(REPO_ROOT, TEST_DIR)
    for dirpath, dirnames, filenames in os.walk(root):
        rel_dir = os.path.relpath(dirpath, root)
        dirnames[:] = [
            d for d in dirnames
            if os.path.normpath(os.path.join(rel_dir, d)) not in TEST_DIR_EXCLUDES
            and d not in TEST_DIR_EXCLUDES
        ]
        for name in filenames:
            files.append(os.path.relpath(os.path.join(dirpath, name), REPO_ROOT))
    return sorted(files)


def _write_windows_icon(python: str) -> None:
    """Render the SVG app icon to the .ico Nuitka needs, with the build venv's Qt."""
    os.makedirs(BUILD_DIR, exist_ok=True)
    script = (
        "import sys\n"
        "from PySide6.QtCore import Qt\n"
        "from PySide6.QtGui import QGuiApplication, QImage, QPainter\n"
        "from PySide6.QtSvg import QSvgRenderer\n"
        "app = QGuiApplication(sys.argv[:1])\n"
        "image = QImage(256, 256, QImage.Format_ARGB32)\n"
        "image.fill(Qt.transparent)\n"
        "painter = QPainter(image)\n"
        "QSvgRenderer(sys.argv[1]).render(painter)\n"
        "painter.end()\n"
        "sys.exit(0 if image.save(sys.argv[2], 'ICO') else 1)\n"
    )
    env = dict(os.environ, QT_QPA_PLATFORM="offscreen")
    subprocess.run([python, "-c", script, os.path.join(REPO_ROOT, ICON_SVG), ICON_ICO], env=env, check=True)


def _nuitka_args(extra_args) -> list:
    # The onefile exe unpacks its runtime to this folder. A fixed path (no
    # {PID}/{TIME}) makes Nuitka keep it between runs, so only the first run
    # pays the unpacking cost. The build id gives each build its own folder so
    # a rebuilt exe never reuses a previous build's files; old folders under
    # the user cache dir's RefacDir/ are safe to delete. Nothing the app writes
    # goes there: user data lives in the app data dir (app_paths).
    build_id = time.strftime("%Y%m%d-%H%M%S")
    args = [
        "--onefile",
        f"--onefile-tempdir-spec={{CACHE_DIR}}/RefacDir/refacdir-{build_id}",
        f"--output-dir={BUILD_DIR}",
        f"--output-filename={EXE_NAME}",
        # Lets Nuitka fetch build helpers (e.g. MinGW on Windows) without prompting.
        "--assume-yes-for-downloads",
        "--enable-plugin=pyside6",
        # The window icon is an SVG, which needs Qt's SVG image format and icon engine.
        "--include-qt-plugins=sensible,imageformats,iconengines",
        # keyring finds its backends, including the OS one, through package
        # metadata entry points; without it every encrypted save fails over to
        # plaintext JSON. pytest finds the pytest-qt plugin the same way.
        "--include-distribution-metadata=keyring",
        "--include-distribution-metadata=pytest",
        "--include-distribution-metadata=pytest-qt",
        # pytest loads its built-in plugins by module name, pytest-qt is only
        # reached through its entry point, and pytest-qt imports QtTest by name.
        "--include-package=_pytest",
        "--include-package=pytest",
        "--include-package=pytestqt",
        "--include-module=PySide6.QtTest",
        # Test modules import it; the app itself never does.
        "--include-module=app_headless",
    ]
    # The user's search functions file is loaded at runtime and can only import
    # what the build contains; its template promises these.
    args += [f"--include-module={m}" for m in USER_FILE_STDLIB_MODULES]
    args += [f"--include-data-dir={d}={d}" for d in DATA_DIRS]
    args += [f"--include-data-files={f}={f}" for f in DATA_FILES]
    args += [f"--include-data-files={f}={f}" for f in _test_tree_files()]
    if sys.platform == "win32":
        args += [
            # No console window when started from Explorer; when started from
            # a terminal, output (e.g. the smoke test's) goes to that terminal.
            "--windows-console-mode=attach",
            f"--windows-icon-from-ico={ICON_ICO}",
        ]
    return [*args, *extra_args, ENTRY]


def _smoke_test() -> None:
    # Run from outside the repo so a passing test can't depend on the checkout,
    # with all app data in a scratch directory so the user's is untouched.
    with tempfile.TemporaryDirectory(prefix="refacdir-smoke-") as scratch:
        env = dict(os.environ)
        env["QT_QPA_PLATFORM"] = "offscreen"
        env["REFACDIR_APP_DATA_DIR"] = scratch
        result = subprocess.run(
            [EXE_PATH, "--smoke-test"], cwd=os.path.expanduser("~"), env=env,
            capture_output=True, text=True, errors="replace",
        )
    sys.stdout.write(result.stdout + result.stderr)
    if result.returncode != 0:
        sys.exit(f"Smoke test failed: `{EXE_PATH} --smoke-test` exited {result.returncode}")


if __name__ == "__main__":
    args = sys.argv[1:]
    if "--current-env" in args:
        args.remove("--current-env")
        python = sys.executable
    else:
        python = _ensure_build_venv()

    if sys.platform == "win32":
        _write_windows_icon(python)
    subprocess.run([python, "-m", "nuitka"] + _nuitka_args(args), cwd=REPO_ROOT, check=True)
    os.makedirs(os.path.dirname(EXE_PATH), exist_ok=True)
    shutil.copy2(os.path.join(BUILD_DIR, EXE_NAME), EXE_PATH)
    _smoke_test()
    print(f"Built {EXE_PATH}")
