
will_run: true

filename_mapping_functions:

- name: "sixty_four_uppercase_hexadecimal"
  type: "HEX"
  args: [64]
- name: "six_lowercase_alphanumeric"
  type: "ALNUM"
  args: [6, true]
- name: "eight_lowercase_alphanumeric_with_underscore"
  type: "ALNUM"
  args: [8, true, "_"]
- name: "four_digits"
  type: "DIGITS"
  args: [4]


filetype_definitions:

- name: "visual_media_file_types"
  extensions: [".png", ".mp4", ".mpg", ".mpeg", ".mov", ".gif", ".jpg", ".jpeg", ".tiff", ".webp", ".webm", ".bmp"]

- name: "media_file_types"
  extensions: [".bmp", ".gif", ".jpeg", ".jpg", ".mkv", ".mov", ".mp3", ".mp4", ".mpeg", ".mpg", ".png", ".tiff", ".webm", ".webp"]


actions:


- type: "DUPLICATE_REMOVER"
  mappings:
  - name: "Downloads duplicates cleaner"
    source_dir: "{{USER_HOME}}\\Downloads"
    select_for_folder_depth: false
    match_dir: false
    recursive: true
    exclude_dirs: ["Telegram Desktop"]
    preferred_delete_dirs: ["d"]


- type: "RENAMER"
  mappings:

  - name: "Ideogram files"
    function: "rename_by_ctime"
    mappings:
    - search_patterns: "{{is_id_filename}}"
      rename_tag: "idg_"
    locations:
    - root: "{{USER_HOME}}\\Downloads"

  - name: "Temp SDWebui files"
    function: "rename_by_ctime"
    mappings:
    - search_patterns: "tmp{{eight_lowercase_alphanumeric_with_underscore}}.png"
      rename_tag: "SDWebui_"
    locations:
    - root: "{{USER_HOME}}\\Downloads"

  - name: "My Stable Diffusion output"
    function: "rename_by_ctime"
    mappings:
    - search_patterns: ["AnimateDiff", "AnimDiff"]
      rename_tag: "AD_"
    - search_patterns: "[0-9]{{four_digits}}-"
      rename_tag:  "SDWebui_"
    - search_patterns: "{{sixty_four_uppercase_hexadecimal}}"
      rename_tag: "hexstring_"
    locations:
    - root: "{{USER_HOME}}\\ComfyUI\\output"
    - root: "{{USER_HOME}}\\stable-diffusion-webui\\log\\images"
    - root: "D:\\stable-diffusion-webui\\log\\images"

  - name: "Random Selection"
    function: "move_files"
    mappings:
    - search_patterns: "{{random_selection}}"
      rename_tag: "{{USER_HOME}}\\randomly_selected_files"
    locations:
    - root: "{{USER_HOME}}\\Downloads"

  - name: "Other Stable Diffusion output"
    function: "rename_by_ctime"
    mappings:
    - search_patterns: ["AnimateDiff", "AnimDiff"]
      rename_tag: "AD_"
    - search_patterns: "{{sixty_four_uppercase_hexadecimal}}"
      rename_tag: "hexstring_"
    - search_patterns: "{{six_lowercase_alphanumeric}}.png"
      rename_tag: "CBox_"
    locations:
    - root: "{{USER_HOME}}\\Downloads"
      exclude_dirs: ["Telegram Desktop"]
    - root: "{{USER_HOME}}\\img\\img_temps\\_to_review"
    - root: "D:\\img"
      exclude_dirs: [
        "_controlnet\\expressions",
        "_controlnet\\symbols"
      ]


- type: "DIRECTORY_FLATTENER"
  mappings:

  - name: "Flatten Downloads into root folder"
    test: false
    search_patterns: "{{any_file}}"
    location:
      root: "{{USER_HOME}}\\Downloads"



- type: "BACKUP"
  mappings:

  - name: "Image backups"
    warn_duplicates: false
    overwrite: false
    test: false
    skip_confirm: true
    backup_mappings:

    - name: "Stable Diffusion Backups"
      source_dir: "{{USER_HOME}}\\stable-diffusion-webui\\log\\images"
      target_dir: "D:\\stable-diffusion-webui\\log\\images"
      mode: "PUSH_AND_REMOVE"
      will_run: false
      file_types: "{{visual_media_file_types}}"
      exclude_dirs: [
      ]
      exclude_removal_dirs: [
        "{{USER_HOME}}\\stable-diffusion-webui\\log\\images\\other",
      ]

    - name: "Other Images Mirror"
      source_dir: "{{USER_HOME}}\\img"
      target_dir: "D:\\img"
      mode: "MIRROR"
      will_run: true
      file_types: "{{visual_media_file_types}}"
      exclude_dirs: [
      ]
      exclude_removal_dirs: [
      ]

- type: "DIRECTORY_OBSERVER"
  mappings:

  - name: "Directory Observer"
    file_types: "{{media_file_types}}"
    sortable_dirs: [
      "{{USER_HOME}}\\content",
    ]
    extra_dirs: [
      "{{USER_HOME}}\\Downloads"
    ]
